# Generated by Django 3.1.2 on 2021-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sou', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='aguacates.jpg', upload_to='images/'),
        ),
    ]
